services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://api.avin.com.np}
    container_name: suvadigital-frontend
    restart: unless-stopped
    ports:
      - "42390:3000"
    networks:
      - suvadigital-net

networks:
  suvadigital-net:
    name: suvadigital-net
    external: true
